version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3004:3000'
      - '5554:5555'
    volumes:
      - ./realDB:/app/realDB
      - ./upload:/app/upload
    command: "npm run start"
    restart: always
